Update cosigned docs with new ClusterImagePolicy usage
sigstore/sigstore-website pull request #147
Opened 2022-04-21 17:39 UTC by DennyHoang

#### Summary
Add supporting documentation on ClusterImagePolicy configuration and usage.

#### Ticket Link
Addressing https://github.com/sigstore/sigstore-website/issues/139

#### Release Note
```release-note
* Added documentation for ClusterImagePolicy configuration and usage
```

2022-04-21 19:08 UTC, vaikas reviewed
Thanks so much!!!

2022-04-21 19:08 UTC, vaikas commented on content/en/cosign/kubernetes.md
> +An image is admitted after it has been validated against all `ClusterImagePolicy` that matches and
Maybe add a link to 'configuring image patterns' below?

2022-04-21 19:08 UTC, vaikas commented on content/en/cosign/kubernetes.md
> +When a policy is selected to be evaluated against for the matched image, the authorities will be used to validate signatures.
s/against for/against/

2022-04-21 19:08 UTC, vaikas commented on content/en/cosign/kubernetes.md
> +If any one authority is satisfied and a signature is validated, the policy is validated.
maybe it's me that 'any one' reads funny, maybe at least one?

2022-04-21 19:08 UTC, vaikas commented on content/en/cosign/kubernetes.md
> +
We should somewhere mention what happens _iff_ an image does not match any policy. It means in current implementation it will fall through to the "old" behaviour, which can result in something like this:
https://github.com/sigstore/cosign/issues/1653

2022-04-21 19:08 UTC, vaikas commented on content/en/cosign/kubernetes.md
> +
This is really for L53, but do we anywhere (I may have missed) mention how you control, aka, what label (and an example on how to enable the validation?)

something like, to enable validation on a namespace `demo`, you would do:
```
kubectl label namespace demo cosigned.sigstore.dev/include=true
```

2022-04-21 19:08 UTC, vaikas commented on content/en/cosign/kubernetes.md
> +When `tlog` key is specified with no value `tlog: {}`, then the public rekor instance will be used.
I think you can just leave it out, as in not specify anything at all?

2022-04-21 19:08 UTC, vaikas commented on content/en/cosign/kubernetes.md
> +When `tlog` key is specified with no value `tlog: {}`, then the public rekor instance will be used.
So, maybe:
When `tlog` is not specified, then the public rekor instance will be used.

2022-04-25 14:59 UTC, DennyHoang commented on content/en/cosign/kubernetes.md
> +
It is mentioned in the `installation` doc under the `cosigned`. But no harm replicating that detail in this doc.

Otherwise, moving that detail to this file and then in the installation doc, I could link it back to this file for that section.

2022-04-25 17:10 UTC, DennyHoang commented
Addressed PR comments:
- Fixed grammar
- Added `Depcreated Cosigned Verification Behavior` Section
- Moved `Enable Cosigned Admission Controller for Namespaces` section to `kubernetes.md` and have it linked from `installation.md` instead
- added "no policy matched" scenario to section `Admission of Images`
- Mentioned currently only supporting ECDSA keys

cc: @vaikas

2022-04-25 17:42 UTC, vaikas approved these changes
Awesome! Thanks for doing this! I'll take a crack at adding documentation for attestations. I'm at an offsite this week though, so will be a bit slower than usual.

2022-04-26 16:07 UTC, hectorj2f requested changes
@DennyHoang Thanks :).
Could you add the last properties added to the CIP e.g. policy ...?

2022-04-27 13:45 UTC, DennyHoang commented
@hectorj2f I have not gotten familiar with the new CIP policy attestation fields yet. So I would prefer adding that documentation in a different PR.

2022-04-28 20:16 UTC, priyawadhwa approved these changes

2022-04-28 21:55 UTC, hectorj2f approved these changes

2022-04-28 23:04 UTC, merged