[docs] Improving Gitsign docs
sigstore/sigstore-website pull request #174
Opened 2022-06-15 18:27 UTC by erikaheidi

#### Summary
This PR brings a few improvements to the Gitsign docs:

- Copy edits / improvements;
- A separate page with instructions on how to inspect signatures (gitsign/inspecting.md) - **needs review to make sure the information is accurate**
- Updated preview images replacing the default Nuxtjs ones - this should fix the preview that shows up whenever we share pages from the documentation.

```release-note
NONE
```

2022-06-15 18:39 UTC, cpanato commented on content/en/community.md
> +You can also keep in touch by joining our [Slack channel](https://sigstore.slack.com). Use [this invite link](https://links.sigstore.dev/slack-invite) to join.
This will be hosted under chainguard domain or under sigstore? If it is under chainguard i think we need to reword this to not say our slack and something as the sigstore slack ...

2022-06-15 18:50 UTC, erikaheidi commented on content/en/community.md
> +You can also keep in touch by joining our [Slack channel](https://sigstore.slack.com). Use [this invite link](https://links.sigstore.dev/slack-invite) to join.
This is on the Sigstore domain! The first version is up at docs.sigstore.dev/gitsign

2022-06-16 02:38 UTC, ltagliaferri commented on content/en/community.md
> +You can also keep in touch by joining our [Slack channel](https://sigstore.slack.com). Use [this invite link](https://links.sigstore.dev/slack-invite) to join.
Yeah this is under the Sigstore domain!

2022-06-16 02:45 UTC, ltagliaferri requested changes
Minor suggestions, thank you for these updates and for updating the preview images too!

2022-06-16 02:45 UTC, ltagliaferri commented on content/en/gitsign/inspecting.md
> +You should see output similar to this:
I would make "see" read as "receive" or something like that for more inclusive language

2022-06-16 02:45 UTC, ltagliaferri commented on content/en/gitsign/installation.md
> +You can install Gitsign for MacOS systems using Homebrew. Use `brew tap` to add Sigstore's repository to your system, then run `brew install` to get it installed:
Homebrew works with Linux and the Windows Subsystem for Linux too, so I would probably write something like this (with link to Homebrew too)

```
If you are using [Homebrew](https://docs.brew.sh/) as a package manager for macOS or Linux, you can use it to install Gistign. Use `brew tap` to add Sigstore's repository to your system, then run `brew install` to get it installed:
```

2022-06-16 07:00 UTC, cpanato commented on content/en/community.md
> +You can also keep in touch by joining our [Slack channel](https://sigstore.slack.com). Use [this invite link](https://links.sigstore.dev/slack-invite) to join.
cool, i dont know maybe was my mistake, but i saw the page under the cg domain. thanks for the clarification and sorry for the mess

2022-06-16 12:20 UTC, erikaheidi commented on content/en/gitsign/inspecting.md
> +You should see output similar to this:
you're 1000% right, thank you! fixing it

2022-06-16 12:58 UTC, merged