Add history / research page, practical links to the overview page
sigstore/sigstore-website pull request #201
Opened 2022-07-24 01:38 UTC by ltagliaferri

#### Summary

Resolves #93 and #156

I added a history and research page, some of this is being brought in from the Sigstore course and is attributed. I think that this could be expanded upon especially in terms of the research side, but I wanted to start the page and do a first pass.

I added practical links to the landing index page of the docs site. 

Additionally, I made some minor stylistic changes to make casing more consistent

#### Release Note

Docs changes

#### Documentation

These are exclusively docs changes

2022-07-24 14:11 UTC, lukehinds requested changes
hold on this, there are a few misconceptions in here I need to highlight.

2022-07-24 17:27 UTC, lukehinds commented on content/en/history.md
> +The transparency log work fed into the Rekor project which began in mid-2020. Luke Hinds, Bob Callaway, and Dan Lorenc are the co-founders of the Sigstore project, which launched in March 2021 with R
The listed projects did 'fed into' the rekor project, it was more that they were in a similar paradigm. When i started work on rekor , it was a fresh code base and none of the ideas above were that influential on the design of rekor. It shares similarities with certificate transparency, but that is largely due to having the same trillian backend. I would say we can drop all of these apart from certificate transparency.  rget had little influence on rekor, that was hashing in binary sha's into certificate transparency whereas rekor started off by recording in-toto provenance and was made to tackle supply chain provenance. They are similar , but positioning it as a precursor is overplaying its influence.

I think we should mention I started the project and Red Hat were the founding company (it was Red Hat who signed off ownership of the project to the Linux Foundation). I have always cited Dan and Bob as co-founders as without them being involved I am under no illusion it would not have been a success that it is. I would be more inclined to say 'Luke Hinds started the project in mid 2020 and was later joined by co-founders Dan Lorenc and Bob Callaway'.

2022-07-24 17:27 UTC, lukehinds commented on content/en/history.md
> +If you would like more of a background about software supply chain security more generally, you can refer to the resources available through the [Software Supply-Chain Security Reading List](https://
the ssc-reading-list is listed twice.

If we going to mention languages, it might be worth having bullets to each language:

* sigstore/sigstore - The Go library
* sigstore/ruby-sigstore - RubyGems Library
* sigstore/maven - A maven library
* sigstore/sigstore-rs A rust sigstore library

2022-07-24 17:27 UTC, lukehinds commented on content/en/index.md
> +**Sigstore empowers software developers to securely sign software artifacts such as release files, container images, binaries, bill of material manifests and more. Signing materials are then stored i
I don't blame you for correcting this, its grammatically correct, however sigstore is actually a lower s, I know it's not written down anywhere though so you would not be expected to know that. When I came up with the name and intended it to be all lower case.

2022-07-24 21:51 UTC, ltagliaferri commented on content/en/history.md
> +The transparency log work fed into the Rekor project which began in mid-2020. Luke Hinds, Bob Callaway, and Dan Lorenc are the co-founders of the Sigstore project, which launched in March 2021 with R
Thank you for the feedback and context, for the Linux Foundation course we based a lot of this off of [this slide deck](https://docs.google.com/presentation/d/1_0P82mi0IR63PktxHnFChhC8iJ_YlDhzaIOAsvR7AHU/edit#slide=id.p) and digging around old blog posts. I think we were trying to balance trying to talk about the work going on in the space alongside some of the history we could find about the project itself, but I can see focusing more on the project itself vs the other supply chain work on this site. 

I will make revisions and update

2022-07-24 21:51 UTC, ltagliaferri commented on content/en/history.md
> +If you would like more of a background about software supply chain security more generally, you can refer to the resources available through the [Software Supply-Chain Security Reading List](https://
I think a separate languages section with bullets would be nice here +1

2022-07-25 16:49 UTC, lukehinds commented on content/en/history.md
> +The transparency log work fed into the Rekor project which began in mid-2020. Luke Hinds, Bob Callaway, and Dan Lorenc are the co-founders of the Sigstore project, which launched in March 2021 with R
Just noticed a typo on my previous comment, I meant to say did **not** feed into. 

I don't know have any insight into the LF course, it was not written by the community and I never had any chance to review any of the content. I don't have access to the slides , but I figure it's from kubecon NA 21, if so I did not entirely agree with how the history was presented there as well.

2022-07-25 17:09 UTC, tracymiranda commented on content/en/history.md
> +The transparency log work fed into the Rekor project which began in mid-2020. Luke Hinds, Bob Callaway, and Dan Lorenc are the co-founders of the Sigstore project, which launched in March 2021 with R
@lukehinds i personally let you know about the course when we met face-to-face and also sent you and rest of TSC a copy to review ahead of publishing so these comments are not quite accurate. Also by community sounds like you are only referring to code-contributors, which imho is a very limiting descriptions. So I think it is fine to say you did not have a chance to review that history and don't fully agree with it but please be aware that I did make every effort to give you and the rest of the TSC the opportunity to and don't think it's great to say the course was not 'written by the community'.

2022-07-25 17:27 UTC, lukehinds commented on content/en/history.md
> +The transparency log work fed into the Rekor project which began in mid-2020. Luke Hinds, Bob Callaway, and Dan Lorenc are the co-founders of the Sigstore project, which launched in March 2021 with R
I honestly have no recollection about a TSC review, so apologies if I was wrong there. I think it still stands though that its not community written material. It was written by a company for fee (which there is nothing wrong with), but either way it's still not community sourced.

2022-07-27 08:01 UTC, lukehinds approved these changes
lgtm, thanks for your work @ltagliaferri

2022-07-27 17:20 UTC, ltagliaferri commented
> lgtm, thanks for your work @ltagliaferri

Thanks for your insight here, really appreciate it!

2022-07-27 17:20 UTC, merged