Fix
sigstore/sigstore-website pull request #270
Opened 2023-04-21 02:33 UTC by Sukriti-sood

# Changes in the readme.

These changes will help newcomers to know how to contribute and center alignment of logo looks better.

2023-04-27 15:06 UTC, Neilblaze commented on README.md
> +The sigstore welcomes contributions. You can submit an issue or pull request if you have an idea for a new feature or a bug fix. Please read the [Contributor Guidelines](/CONTRIBUTORS.md) as well.
Maybe we can update this to 👇🏼 

Community contributions are welcome & encouraged. To suggest a new feature or report a bug, please feel free to submit an issue or a pull request. Prior to contributing, we recommend reviewing our [Contributor Guidelines](/CONTRIBUTORS.md).

2023-04-27 15:06 UTC, Neilblaze commented on README.md
> +<div align="center">
While I don't think this change is a top priority, overall it looks good. I do have a minor nitpick, however: if we do decide to include this change, it would be better to exclude the `# sigstore-website` header title as it could appear inconsistent.

@ltagliaferri & @haydentherapper any thoughts on this?

2023-04-27 15:07 UTC, Neilblaze commented
Also, @Sukriti-sood would you mind updating the PR title? (maybe add a little info about what this PR does)

2023-04-27 17:29 UTC, ltagliaferri commented on README.md
> +The sigstore welcomes contributions. You can submit an issue or pull request if you have an idea for a new feature or a bug fix. Please read the [Contributor Guidelines](/CONTRIBUTORS.md) as well.
```suggestion
Community contributions are welcome. To suggest a new feature or report a bug, please feel free to submit an issue. Prior to contributing, please review our [Contributor Guidelines](https://github.com/CONTRIBUTORS.md).
```

2023-04-27 17:30 UTC, ltagliaferri commented on README.md
> +<div align="center">
Let's not use HTML on a Markdown README file

2023-04-27 17:36 UTC, ltagliaferri requested changes
Some changes requested here. I would avoid HTML in a Markdown file that lives on GitHub. In the future, please open an issue to discuss prior to opening a pull request.

2023-04-27 17:36 UTC, ltagliaferri commented on README.md
> +    <img src="https://github.com/sigstore/sigstore-website/blob/main/assets/icons/logo.svg" alt='logo'>
Let's not use HTML on the README file

2023-04-27 17:36 UTC, ltagliaferri commented on README.md
> +## How to Get Involved?
This shouldn't have a question mark

```suggestion
## How to Get Involved
```

2023-04-28 01:42 UTC, Sukriti-sood commented
> Some changes requested here. I would avoid HTML in a Markdown file that lives on GitHub. In the future, please open an issue to discuss prior to opening a pull request.

My apologies, I will open issues first next time.

2023-05-09 20:18 UTC, ltagliaferri approved these changes

2023-06-22 21:24 UTC, merged