refresh events on sigstore website with newer events.
sigstore/sigstore-website pull request #277
Opened 2023-06-06 21:03 UTC by jonvnadelberg

Fix for issue #276 

#### Summary

Events were out out date on website, and did not include important recent events.  this pr places them on website.
#### Release Note

NONE
#### Documentation

doc only

2023-06-06 21:04 UTC, jonvnadelberg commented
@haydentherapper @ltagliaferri  Please review added events.

2023-06-06 21:51 UTC, haydentherapper commented on content/events/sigstore-npm-beta.md
> +title: Sigstore npm public beta released
```suggestion
title: Sigstore support in npm released in public beta
```

2023-06-06 21:51 UTC, haydentherapper commented on content/events/sigstore-python-1-0.md
> +title: Sigstore-Python 1.0 released
```suggestion
title: sigstore-python 1.0 released
```

2023-06-08 16:36 UTC, haydentherapper approved these changes

2023-06-13 12:55 UTC, ltagliaferri requested changes
Just a date typo here

2023-06-13 12:55 UTC, ltagliaferri commented on content/events/cosign-2-0-launch.md
> +pubDate: 20233-02-23
```suggestion
pubDate: 2023-02-23
```

2023-06-15 16:50 UTC, jonvnadelberg commented
@ltagliaferri date typo fixed on pr #277 can we merge?

2023-06-22 19:36 UTC, jonvnadelberg commented
Hi @ltagliaferri can this be merged now?   It looks to be done.

2023-06-22 21:25 UTC, ltagliaferri approved these changes

2023-06-22 21:25 UTC, merged